### ISSUE TITLE
Unable to download labels for something-something V2

### ISSUE THREAD

**Issue by chengruizhe** [TwentyBN/something-something-v2-baseline#14]
When I try to download the labels from [here](https://20bn.com/datasets/something-something), the download always gets stuck after getting the first 900kb and fails due to a network error. I tried multiple browsers and computers. I could download the data with no problem, but not the labels. Can I get some help with this? Thanks.

**Comment by anirban-code-to-live** [comment]
I am also facing the same issue. Could the dataset moderators kindly check the issue.

**Comment by s-gv** [comment]
Same here. I'm able to download the videos but not the labels (network error after 2.6 MB for train.json)

**Comment by njulus** [comment]
I am also faced with this problem. Could you please check this issue? Thank you.

**Comment by raghavgoyal14** [comment]
I have escalated this issue to the relevant personnel at 20bn. I'll keep you posted if there's any update on the issue.

**Comment by ingooooooo** [comment]
The problem has been fixed. Please try again. Sorry for inconvenience!
