### ISSUE TITLE
predicting with notebook

### ISSUE THREAD

**Issue by Shanmugavadivelugopal** [TwentyBN/something-something-v2-baseline#9]
I started replicating the given notebook's implementation.When i do so, i got 
`---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-22-892f9596470e> in <module>()
     21                        transform_pre=transform_eval_pre,
     22                        transform_post=transform_post,
---> 23                        get_item_id=True,
     24                        )
     25 dict_two_way = val_data.classes_dict

/content/drive/My Drive/SOMETHING/model/data_loader_av.py in __init__(self, root, json_file_input, json_file_labels, clip_size, nclips, step_size, is_val, transform_pre, transform_post, augmentation_mappings_json, augmentation_types_todo, get_item_id, is_test)
     20                  get_item_id=False, is_test=False):
     21         self.dataset_object = WebmDataset(json_file_input, json_file_labels,
---> 22                                           root, is_test=is_test)
     23         self.json_data = self.dataset_object.json_data
     24         self.classes = self.dataset_object.classes

/content/drive/My Drive/SOMETHING/model/data_parser.py in __init__(self, json_path_input, json_path_labels, data_root, is_test)
     80         EXTENSION = ".webm"
     81         super().__init__(json_path_input, json_path_labels, data_root,
---> 82                          EXTENSION, is_test)
     83 
     84 

/content/drive/My Drive/SOMETHING/model/data_parser.py in __init__(self, json_path_input, json_path_labels, data_root, extension, is_test)
     21 
     22         # preparing data and class dictionary
---> 23         self.classes = self.read_json_labels()
     24         self.classes_dict = self.get_two_way_dict(self.classes)
     25         self.json_data = self.read_json_input()

/content/drive/My Drive/SOMETHING/model/data_parser.py in read_json_labels(self)
     55     def read_json_labels(self):
     56         classes = []
---> 57         with open(self.json_path_labels, 'rb') as jsonfile:
     58             json_reader = json.load(jsonfile)
     59             for elem in json_reader:

FileNotFoundError: [Errno 2] No such file or directory: '/data-ssd1/20bn-something-something-v2/annotations/something-something-v2-labels.json'`

Is there any suggestions regarding this?
Thanks in advance

**Comment by raghavgoyal14** [comment]
You need to download the json files and edit the path to these json files in config

ref: https://github.com/TwentyBN/something-something-v2-baseline#setting-up
